#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-libsoup-soname-24
Version  : 2.74.0
Release  : 48
URL      : https://download.gnome.org/sources/libsoup/2.74/libsoup-2.74.0.tar.xz
Source0  : https://download.gnome.org/sources/libsoup/2.74/libsoup-2.74.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0
Requires: compat-libsoup-soname-24-lib = %{version}-%{release}
Requires: compat-libsoup-soname-24-license = %{version}-%{release}
Requires: compat-libsoup-soname-24-locales = %{version}-%{release}
Requires: glib-networking
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : curl
BuildRequires : curl-dev32
BuildRequires : e2fsprogs-dev
BuildRequires : e2fsprogs-dev32
BuildRequires : glib-networking
BuildRequires : glib-networking-lib32
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : libpsl-dev32
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : sqlite-autoconf-dev32
BuildRequires : vala
BuildRequires : vala-dev
BuildRequires : zlib-dev
BuildRequires : zlib-dev32

%description
libsoup is an HTTP client/server library for GNOME. It uses GObjects
and the glib main loop, to integrate well with GNOME applications.

%package lib
Summary: lib components for the compat-libsoup-soname-24 package.
Group: Libraries
Requires: compat-libsoup-soname-24-license = %{version}-%{release}

%description lib
lib components for the compat-libsoup-soname-24 package.


%package license
Summary: license components for the compat-libsoup-soname-24 package.
Group: Default

%description license
license components for the compat-libsoup-soname-24 package.


%package locales
Summary: locales components for the compat-libsoup-soname-24 package.
Group: Default

%description locales
locales components for the compat-libsoup-soname-24 package.


%prep
%setup -q -n libsoup-2.74.0
cd %{_builddir}/libsoup-2.74.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632332680
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain --wrap-mode=nodownload \
-Dgssapi=disabled \
-Dinstalled_tests=true  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libsoup-soname-24
cp %{_builddir}/libsoup-2.74.0/COPYING %{buildroot}/usr/share/package-licenses/compat-libsoup-soname-24/ba8966e2473a9969bdcab3dc82274c817cfd98a1
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libsoup
## Remove excluded files
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-address.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-auth-domain-basic.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-auth-domain-digest.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-auth-domain.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-auth-manager.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-auth.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-autocleanups.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-cache.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-content-decoder.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-content-sniffer.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-cookie-jar-db.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-cookie-jar-text.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-cookie-jar.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-cookie.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-date.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-enum-types.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-form.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-headers.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-hsts-enforcer-db.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-hsts-enforcer.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-hsts-policy.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-logger.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-message-body.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-message-headers.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-message.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-method.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-misc.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-multipart-input-stream.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-multipart.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-password-manager.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-portability.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-proxy-resolver-default.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-proxy-resolver.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-proxy-uri-resolver.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-request-data.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-request-file.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-request-http.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-request.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-requester.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-server.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-session-async.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-session-feature.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-session-sync.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-session.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-socket.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-status.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-tld.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-types.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-uri.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-value-utils.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-version.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-websocket-connection.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-websocket-extension-deflate.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-websocket-extension-manager.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-websocket-extension.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-websocket.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-xmlrpc-old.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup-xmlrpc.h
rm -f %{buildroot}/usr/include/libsoup-2.4/libsoup/soup.h
rm -f %{buildroot}/usr/include/libsoup-gnome-2.4/libsoup/soup-cookie-jar-sqlite.h
rm -f %{buildroot}/usr/include/libsoup-gnome-2.4/libsoup/soup-gnome-features.h
rm -f %{buildroot}/usr/include/libsoup-gnome-2.4/libsoup/soup-gnome.h
rm -f %{buildroot}/usr/lib64/girepository-1.0/Soup-2.4.typelib
rm -f %{buildroot}/usr/lib64/girepository-1.0/SoupGNOME-2.4.typelib
rm -f %{buildroot}/usr/lib64/libsoup-2.4.so
rm -f %{buildroot}/usr/lib64/libsoup-gnome-2.4.so
rm -f %{buildroot}/usr/lib64/pkgconfig/libsoup-2.4.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/libsoup-gnome-2.4.pc
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/cache-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/chunk-io-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/chunk-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/coding-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/context-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/continue-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/cookies-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/date-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/forms-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/header-parsing-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/hsts-db-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/hsts-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/index.txt
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/libtest-utils.so
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/misc-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/multipart-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/no-ssl-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/ntlm-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/ntlm-test-helper
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/redirect-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/requester-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/resource-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/samesite-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/server-auth-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/server-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/session-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/sniffing-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/socket-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/soup-tests.gresource
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/ssl-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/streaming-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/test-cert.pem
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/test-key.pem
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/timeout-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/tld-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/uri-parsing-test
rm -f %{buildroot}/usr/libexec/installed-tests/libsoup-2.4/websocket-test
rm -f %{buildroot}/usr/share/gir-1.0/Soup-2.4.gir
rm -f %{buildroot}/usr/share/gir-1.0/SoupGNOME-2.4.gir
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/cache-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/chunk-io-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/chunk-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/coding-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/context-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/continue-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/cookies-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/date-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/forms-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/header-parsing-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/hsts-db-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/hsts-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/misc-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/multipart-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/no-ssl-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/ntlm-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/redirect-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/requester-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/resource-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/samesite-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/server-auth-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/server-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/session-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/sniffing-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/socket-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/ssl-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/streaming-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/timeout-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/tld-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/uri-parsing-test.test
rm -f %{buildroot}/usr/share/installed-tests/libsoup-2.4/websocket-test.test
rm -f %{buildroot}/usr/share/vala/vapi/libsoup-2.4.deps
rm -f %{buildroot}/usr/share/vala/vapi/libsoup-2.4.vapi

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsoup-2.4.so.1
/usr/lib64/libsoup-2.4.so.1.11.1
/usr/lib64/libsoup-gnome-2.4.so.1
/usr/lib64/libsoup-gnome-2.4.so.1.11.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libsoup-soname-24/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files locales -f libsoup.lang
%defattr(-,root,root,-)

